channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - cmake
  - pybind11
  - pinocchio
  - opencv
  - pip
  - pip:
  # the following packages are installed in requirements.txt
    # - numpy <1.24 # certain deprecated operations were used in other deps
    # - scipy
    # - sophuspy
    # - pybullet
    # - trimesh
    # - pytest
    # - scikit-image
    # - scikit-fmm
    # - scikit-learn
    # - numpy-quaternion
    # - natsort
    # # Neural networks
    # - openai-clip
    # - timm
    # - pandas
    # # visualizations and debugging
    # - matplotlib
    # # Command line tools
    # - click
    # # data tools
    # - yacs
    # - h5py
    # - imageio
    # - pygifsicle
    # - pynput
    # - git+https://github.com/openai/CLIP.git
